FlatsKG/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('chats/', include('chats.urls')),
    path('listings/', include('listings.urls')),
    path('common/', include('common.urls')),
    path('support/', include('support.urls')),
    path('', lambda request: redirect('listings/all', permanent=True)),
    path('accounts/', include('django.contrib.auth.urls')),
    path('custom_admin/', include('custom_admin.urls')),
]

chats/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('my_chats/', views.my_chats, name='my_chats'),
    path('start_chat/<int:user_id>/', views.start_chat, name='start_chat'),
    path('room/<int:room_id>/', views.chat_room, name='chat_room'),
]

users/urls.py
from django.urls import path
from .views import profile_view, RegisterUser, show_user_profile, change_password, change_password_view
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path('profile/', profile_view, name='profile'),
    path('register/', RegisterUser.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('profile_<int:user_id>/', show_user_profile, name='another_profile'),
    path('change_password', change_password, name='change_password'),
    path('change-password-view/', change_password_view, name='change_password_view'),
]

templates/base_generic.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Flats KG{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.0.0/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <script src="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.4/dist/aos.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

    {% block extra_css %}{% endblock %}
    <style>
        #mobile-menu {
            opacity: 0;
            transform: translateY(-20px);
            transition: opacity 0.3s ease-out, transform 0.3s ease-out, visibility 0.3s ease-out;
            visibility: hidden;
            display: none;
        }

        #mobile-menu.open {
            opacity: 1;
            transform: translateY(0);
            visibility: visible;
            display: block;
        }
    </style>
</head>
<body class="flex flex-col min-h-screen">

<nav class="bg-gradient-to-r from-gray-800 to-gray-900 p-4 shadow-lg">
    <div class="container mx-auto flex justify-between items-center">
        <div class="flex items-center">
            <a href="{% url 'all_listings' %}"
               class="text-white text-2xl font-bold hover:text-gray-300 transition duration-300 flex items-center">
                <i class="fa-regular fa-building mr-2"></i> flats.kg
            </a>
        </div>

        <div class="hidden md:flex items-center justify-center space-x-14 mx-4">
            <a href="{% url 'about' %}"
               class="text-white text-2xl font-bold hover:text-gray-300 transition duration-300">
                О нас
            </a>
            <a href="{% url 'support' %}"
               class="text-white text-2xl font-bold hover:text-gray-300 transition duration-300">
                Поддержка
            </a>
        </div>

        <div class="hidden md:flex items-center space-x-4">
            {% if not user.is_authenticated %}
                <a href="{% url 'login' %}"
                   class="py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition">
                    Вход
                </a>
                <a href="{% url 'users:register' %}"
                   class="py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition">
                    Регистрация
                </a>
            {% else %}
                <a href="{% url 'users:profile' %}"
                   class="inline-block py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition">
                    Профиль
                </a>
                <form action="{% url 'users:logout' %}" method="post" class="inline">
                    {% csrf_token %}
                    <button type="submit"
                            class="inline-block py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition">
                        Выйти
                    </button>
                </form>
            {% endif %}
        </div>

        <div class="md:hidden flex items-center">
            <button id="menu-toggle" class="text-white focus:outline-none">
                <i class="fa-solid fa-bars text-2xl"></i>
            </button>
        </div>
    </div>

    <div id="mobile-menu" class="md:hidden mt-4 px-4">
        <a href="{% url 'about' %}"
           class="block text-white text-xl font-bold hover:text-gray-300 transition duration-300 py-3">
            О нас
        </a>
        <a href="{% url 'support' %}"
           class="block text-white text-xl font-bold hover:text-gray-300 transition duration-300 py-3">
            Поддержка
        </a>
        {% if not user.is_authenticated %}
            <a href="{% url 'login' %}"
               class="inline-block py-2 px-6 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition mt-2 mr-3">
                Вход
            </a>
            <a href="{% url 'users:register' %}"
               class="inline-block py-2 px-6 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition mt-2">
                Регистрация
            </a>
        {% else %}
            <a href="{% url 'users:profile' %}"
               class="inline-block py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition mr-3">
                Профиль
            </a>
            <form action="{% url 'users:logout' %}" method="post" class="inline">
                {% csrf_token %}
                <button type="submit"
                        class="inline-block py-2 px-4 bg-yellow-400 text-white font-semibold rounded-md hover:bg-yellow-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 transition">
                    Выйти
                </button>
            </form>
        {% endif %}
    </div>
</nav>

<main class="flex-grow flex items-center justify-center bg-gray-50">
    {% block content %}{% endblock %}
</main>

<footer class="bg-gradient-to-r from-gray-800 to-gray-900 text-white py-6 shadow-lg">
    <div class="container mx-auto text-center">
        <p class="text-lg font-semibold">&copy; 2025 Flats KG</p>
    </div>
</footer>

<script>
    document.getElementById('menu-toggle').addEventListener('click', function () {
        var mobileMenu = document.getElementById('mobile-menu');
        if (mobileMenu.classList.contains('open')) {
            mobileMenu.classList.remove('open');
            setTimeout(function () {
                mobileMenu.style.display = 'none';
            }, 300);
        } else {
            mobileMenu.style.display = 'block';
            setTimeout(function () {
                mobileMenu.classList.add('open');
            }, 10);
        }
    });
</script>

{% block extra_js %}{% endblock %}
</body>
</html>